### ISSUE TITLE
Not Working in 0.116

### ISSUE THREAD

**Issue by JohnZable** [iantrich/text-divider-row#12]
**Checklist:**

- [X ] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**
0.116
**Last working release (if known):**
0.115.6
**Browser and Operating System:**

FireFox 81.0.1 on Windows 10
     HomeAssistant Server: Debian Buster VENV Install
**Description of problem:**
text-divider-row does not show anything in LoveLace web page.

text-divider-row does not show anything in LoveLace web page.  The page is displayed as if there is no reference to text-divider-row in the .yaml file.
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by iantrich** [comment]
Do you see `TEXT-DIVIDER-ROW` was printed in the browser console?

**Comment by iantrich** [comment]
I brought up my devcontainer and am unable to replicate. resource is loading just fine

**Comment by JohnZable** [comment]
Hi;
No, I do not see that.

Thank You,John

    On Tuesday, October 20, 2020, 7:06:23 AM PDT, Ian Richardson <notifications@github.com> wrote:  
 
 


Do you see TEXT-DIVIDER-ROW was printed in the browser console?

**Comment by JohnZable** [comment]
Hi;
Hmmmm.  This has been working for many, many months.  The only things I did were update HomeAssistant and when it did not show up, I updated all of my resources listed in configuration.yaml.  Nothing changed.  Then, since I was using vertical-stack-in-card, which was throwing an error covered in the blog on one of my pages and it appears to not be maintained, I switched to stack-in-card and updated my lovelace yaml files for this change.
I was stumped and had found someone reference the same issue, though I forget where.  Nobody gave an actual response to the person, other than assuming they were a noob and providing basic information I had already used.  I noticed text-divider-row had not been updated in a few months and thought the issue might be the Custom Lovelace Cards Breaking Change listed in the release.  It was then I created a bug report, which is something I rarely do.
It would be nice if the log showed me some error.  I do not even see an error when I inspect and debug the web page from the browser.  I see no mention of anything to do with text-divider row.
I guess I need to do some more head scratching on this one.

Thank You,John Zable

    On Tuesday, October 20, 2020, 1:59:41 PM PDT, Ian Richardson <notifications@github.com> wrote:  
 
 


I brought up my devcontainer and am unable to replicate. resource is loading just fine

**Comment by JohnZable** [comment]
Hi;
So, for some reason I had to add "javascript_version: latest" under the "frontend" section of configuration.yaml.  I had never had that there, since the default "auto" always worked before.  I am bewildered that I now have to add a deprecated configuration variable into the system after an upgrade, but oh well.  At least I got it working.  (I do love having the text divider separating groups of entities again without having to use a new card.)


Thank You,John Zable

    On Tuesday, October 20, 2020, 1:59:41 PM PDT, Ian Richardson <notifications@github.com> wrote:  
 
 


I brought up my devcontainer and am unable to replicate. resource is loading just fine

**Comment by JohnZable** [comment]
I am not sure if the new frontend fix mentioned will fix this, but since this is related to the frontend and appears to not be specific to text-divider-row, I am closing this issue.

Thank You,
John Zable
