### ISSUE TITLE
font-size 

### ISSUE THREAD

**Issue by JamesMcCarthy79** [iantrich/text-divider-row#3]
I would like to request the ability to be able to change font size and height of the card to better reduce to blank space absorbed by this entity row.

**Comment by iantrich** [comment]
Have you tried applying card-modder to it?

**Comment by DavidFW1960** [comment]
> Have you tried applying card-modder to it?

So same as with the line/text colour.... some of us try to not use too many custom cards... so using yet another custom card to provide a basic function like colour or font size doesn't make much sense.

**Comment by iantrich** [comment]
Having every developer provide a full suite of customizations for each card is far from the answer as well. I dont plan to add it but PRs are welcome

**Comment by DavidFW1960** [comment]
So why ask @JamesMcCarthy79 to open an issue (as you did on the forum) when you have no intention of fixing it then? Not everyone has the ability to write code/PR's.

**Comment by iantrich** [comment]
Just because I won't personally do it (at least at this time) doesn't mean I want to hide the request. I didn't ask you or him specifically to create a PR, but anyone is open to create PRs on any of my cards and resolve issues.

**Comment by dannymertens** [comment]
Hi,

I would like to make the divider line white, can somebody help me how to this with card-mod: https://github.com/thomasloven/lovelace-card-mod, sorry but quite new to this all and not so easy to understand for a novice I'm afraid :-(

Thanks!

**Comment by mirekmal** [comment]
Revisiting this topic... Can we have text font lighter (or some user control over it)? Now it seems to be bold so it looks way heavier than even standard card headers... does not look good. I tried to use card-modder but is seems not to be deprecated. Card mod works only on cards, not rows, so to apply it it makes things overly complicated/nested within. So it makes impossible to achieve reasonable UI aestetics :-(

**Comment by iantrich** [comment]
Added theme variable in 1.4.0 (will need to reinstall as I have moved the repo from custom-cards to my personal). I'm in the process of getting it added to [default HACS](https://github.com/hacs/default/pull/534)
